# Generated by Django 5.1.7 on 2025-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
